baseURL = "https://gs-ghy.netlify.app"
languageCode = "en-us"
title = "GirlScript Guwahati"

theme = "bittersteel"

[markup]
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
style = "friendly"
tabWidth = 4

[permalinks]
pages = "/:title/"
blogs = "/:year/:title/"
